### PR TITLE
ci: enable testing on arm64 

### PR DESCRIPTION
**Pull request by LaszloGombos**
Enable testing on arm64 using the Debian container.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
I would prefer to have Fedora and Debian tested in both architectures.

**Comment by Conan-Kudo** [comment]
We could use native AArch64 machines couldn't we?

**Comment by bdrung** [comment]
I have no clear preference whether the arm64 tests should run on Debian or Ubuntu, but please keep the amd64 tests. Then it will be easier to nail down failures (i.e. is the failure on the distro or the arch?).

**Comment by bdrung** [comment]
AArch64 runners are in beta: https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

A note from my tests to run the tests on other architectures: The IDE device needs to be replaced by virtio. See https://github.com/dracutdevs/dracut/issues/2493

**Comment by Conan-Kudo** [comment]
No, I think you're fine, but let's not make Debian not get tested on x86_64. Maybe a second matrix for ARM?

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
