### PR TITLE
Erofs tests

### PR DESCRIPTION
**Pull request by bcl**
## Changes

Adds testing for erofs support in dmsquash-live, makes sure the erofs kernel module is installed when using dmsquash-live.

## Checklist
- [X] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [X] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by bcl** [comment]
This needs new containers with erofs-utils installed (one of the commits adds this), so I'm not sure if testing will pass at all...

**Comment by LaszloGombos** [comment]
@bcl  Can you please separate the Dockerfile change into its own PR, that way I can help just landing that.

CI has a limitation where the Dockerfile changes needs to land first before they are available on the CI.

**Comment by LaszloGombos** [comment]
Gentoo container changes do not build for some reason

> 3.002 - sys-fs/erofs-utils-1.7::gentoo (masked by: ~amd64 keyword)
> 3.002 - sys-fs/erofs-utils-1.6-r1::gentoo (masked by: ~amd64 keyword)

CC @AndrewAmmerlaan

**Comment by LaszloGombos** [comment]
Rebased...

**Review by Conan-Kudo — APPROVED** [review]
This seems reasonable. Knowing that arch-12 is flaky, I'll merge it after opensuse passes.

**Pull request merged**
