### PR TITLE
chore: remove deprecated command line options

### PR DESCRIPTION
**Pull request by jozzsi**
Remove handling for the following command line options

- rdbreak
- rd.ccw
- rd_CCW
- rd_DASD_MOD
- rd_DASD
- rdinitdebug rdnetdebug
- rd_DM_UUID
- rdblacklist
- rdinsmodpost
- rdloaddriver
- rd_NO_FSTAB
- rdinfo
- check
- rdlivedebug
- live_dir
- liveimg
- overlay
- readonly_overlay
- reset_overlay
- live_ram
- rd_NO_CRYPTTAB
- rd_LUKS_KEYDEV_UUID
- rd_LUKS_KEYPATH
- rd_NO_LUKS
- rd_LUKS_UUID
- rd_NO_LVMCONF
- rd_LVM_LV
- rd_NO_LVM
- rd_LVM_VG
- rd_NFS_DOMAIN
- rd_NO_PLYMOUTH
- rd_retry
- rdshell
- rd_NO_SPLASH
- rd_NO_ZFCPCONF
- rd_ZFCP
- rd_ZNET

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by lnykryn** [comment]
Honestly, I have a bad feeling about this, but unfortunately, that's all I have. We don't have any hard data about what people use on the kernel cmdline.
I tried to go through the code of some dependent components, namely Anaconda and Lorax, and I don't think they use any of these, but I would be careful around "liveimg" and "overlay".
On the other hand, we had a deprecation warning there for a long time, so if we remove those, I don't think users can blame us if we remove them and something breaks.

**Comment by LaszloGombos** [comment]
CC also @AdamWill for input on compat.

**Comment by mwilck** [comment]
IMO this is fair. I haven't seen any of these options being used for years.

**Comment by AdamWill** [comment]
yeah...I kinda agree with both @lnykryn and @mwilck , it feels pretty much inevitable that this will break *someone*, but I can't find anything it breaks in the obvious places. On the whole, I'd say let's try and it and see. It's easy enough to revert something if necessary.

**Comment by pvalena** [comment]
LGTM.

**Review by pvalena — APPROVED** [review]

**Review by LaszloGombos — APPROVED** [review]
Thanks everyone for helping with the reviews and checking the usage of these arguments.

**Review by Conan-Kudo — APPROVED** [review]
This gives me the heebie-jeebies, but let's try it anyway...

**Pull request merged**
