### PR TITLE
fix(dracut-init.sh): clarify the error message

### LINKED ISSUE #329: dracut[E]: Module 'systemd-pcrphase' depends on 'tpm2-tss', which can't be installed
**Describe the bug**
It seems like the systemd-pcrphase module always gets pulled into the initramfs even if it is not needed as of #256 

This results in the below message on Arch for most users.
```
dracut[E]: Module 'systemd-pcrphase' depends on 'tpm2-tss', which can't be installed
```

This was noticed by EndeavourOS user [here](https://forum.endeavouros.com/t/dracut-error/55999).  I have verified that it also occurs on a base Arch install.

This could be expected behavior but is somewhat unfortunate that most users see this message since it is probably somewhat uncommon to have `tpm2-tools` installed.

**Distribution used**
Arch Linux, EndeavourOS

**Dracut version**
102

**Init system**
systemd

**To Reproduce**
Run dracut in Arch.  Since systemd-pcrextend is part of the systemd package, it will always try to pull in this module.

### PR DESCRIPTION
**Pull request by LaszloGombos**
## Changes

Clarify that dracut module is missing and not Linux command or package.

This will help clarify to the users what action to take as a response of this message - 

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #329

CC @dalto8

### CODE REVIEW

**Comment by dalto8** [comment]
I think the confusion is mostly caused by the fact that this is an error and not a warning.

**Comment by LaszloGombos** [comment]
Looking at https://forum.endeavouros.com/t/dracut-error/55999

```
sudo pacman -S tmp2-tss
```

**Comment by dalto8** [comment]
I see.  Yes, that person is trying to install the wrong thing.

**Comment by Conan-Kudo** [comment]
Is this really `perf`?

**Review by Conan-Kudo — APPROVED** [review]

**Comment by bdrung** [comment]
It would be even nicer if the error message would say which binary wasn't found on the system.

**Pull request merged**
