### PR TITLE
fix(network): call both check_module and module_check

### PR DESCRIPTION
**Pull request by jozzsi**
Add back testing the module with check_module as well as module_check.

Follow-up to c4b57722fb

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

### CODE REVIEW

**Comment by jozzsi** [comment]
> @jozzsi I realize this is still a draft PR. Please include a description on how to reproduce the problem that you're resolving with this PR - especially as it seems to be some back and forth changes in this area. Thanks !

Without this PR, one some Linux distributions (e.g. Void) adding `network` meta module no longer works and fails with the following error

```
dracut[D]: Module 'dbus-broker' will not be installed, because command 'busctl' could not be found!
dracut[D]: Module 'dbus-daemon' will not be installed, because command 'busctl' could not be found!
dracut[E]: Module 'dbus' depends on module 'dbus-daemon', which can't be installed
dracut[E]: Module 'network-manager' depends on module 'dbus', which can't be installed
dracut[E]: Module 'network' depends on module 'network-manager', which can't be installed
```

**Review by LaszloGombos — APPROVED** [review]
thanks

**Comment by sergio-correia** [comment]
> > @jozzsi I realize this is still a draft PR. Please include a description on how to reproduce the problem that you're resolving with this PR - especially as it seems to be some back and forth changes in this area. Thanks !
> 
> Without this PR, on some Linux distributions (e.g. Void) adding `network` meta module no longer works and fails with the following error
> 
> ```
> dracut[D]: Module 'dbus-broker' will not be installed, because command 'busctl' could not be found!
> dracut[D]: Module 'dbus-daemon' will not be installed, because command 'busctl' could not be found!
> dracut[E]: Module 'dbus' depends on module 'dbus-daemon', which can't be installed
> dracut[E]: Module 'network-manager' depends on module 'dbus', which can't be installed
> dracut[E]: Module 'network' depends on module 'network-manager', which can't be installed
> ```

Interestingly, with this change I experience the opposite on Fedora: with it, I am unable to add the `network` module, as the added `check_module()` call will fail.

**Comment by sergio-correia** [comment]
> @sergio-correia - if/when you have a chance, it would be best to test v106 release - sadly it is not yet released on Fedora - see https://src.fedoraproject.org/rpms/dracut/pull-request/74

Hi there, thanks for the pointer. I just tested a local build of 106 now and the results do not change.

The test is fairly simple:
1) `dracut -f --add network` <- this works
2)  If we have a config file instead, it does not work:
```
cat /etc/dracut.conf.d/01-network.conf
dracutmodules+=" network "
```
```
dracut -f
dracut[E]: Module 'network' depends on module 'network-legacy', which can't be installed
dracut[E]: Module 'network' cannot be installed.
```

If I revert this patch (i.e., remove the `&& check_module "$module"` bit in `40network/module-setup.sh`), it works. 

Would you like me to open a separate issue to track this?

**Pull request merged**
