### PR TITLE
feat(pcmcia): only include when another module requires it

### PR DESCRIPTION
**Pull request by LaszloGombos**
## Changes

While the module itself is relativly new the technology is rarely used any more as part of the boot process.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
The commit message needs to be restructured like so: `feat(pcmcia): only include when another module requires it`

**Comment by LaszloGombos** [comment]
Thanks, done !

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
test-12 / gentoo failed?

**Comment by LaszloGombos** [comment]
All green. Landing.

**Pull request merged**
